### ISSUE TITLE
Suggestions for 2018?

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#241]

**Comment by trebmuh** [comment]
I'd suggest to keep it between 2017 and 2019. Then, people will only have to remember that it is the same than 1018, only adding +1000 .

HTH :smile:

**Comment by eldelacajita** [comment]
Now, to the serious stuff 😆 

I talked with @MartinDelille about creating this post because, as a newcomer, I found it very difficult to jump in and contribute without knowing the main goals or needs of the project. I started making proposals for communication and then found out that communication wasn't a priority at all. 

Right now, #232 (and [#1171](https://github.com/liberapay/liberapay.com/issues/1171)) has become the top priority of the project, but it's being handled by the core team, and it's not easy to contribute beyond ideas, feedback and general debate. 

Is there anything else we could be working on right now, or during this year?

**Comment by jorgesumle** [comment]
> I started making proposals for communication and then found out that communication wasn't a priority at all.

Sorry for that, but don't worry, we can study that proposals after we solve our problem with payment processors.

> Is there anything else we could be working on right now, or during this year?

If there is an open issue, there is work to do. You can have a look at the following issues, they should be easy for starters:

- https://github.com/liberapay/liberapay.com/labels/Documentation
- https://github.com/liberapay/liberapay.com/labels/good%20first%20issue

If you make some documentation changes, but you have issues with the source code or submitting a pull request, just ask us, we are happy to help. 

If by any chance you speak Esperanto, I need someone to review my latest translation proposals and fuzzy translations in Weblate.

**Comment by MartinDelille** [comment]
Ok I close it then!

**Comment by eldelacajita** [comment]
Thanks again, @jorgesumle, for being so helpful. I was rather looking for a more general discussion about the mid-term direction and priorities of the project, but I guess they will arise on the go ;)
