### ISSUE TITLE
Going crypto

### ISSUE THREAD

**Issue by techtonik** [liberapay/salon#247]
It seems that in order to survive #232 LP should do this:

1. Identify where people are coming from (country)
2. Detect if crypto in this country is legal or not regulated
3. Do everything in crypto

If Ethereum is chosen, LP can set gas price of 1 gwei, which is roughly $1 per 100 send transactions. One block can contain 300 transactions, and because of volume, it might still be attractive for miners to include this transaction. Or maybe some miners could include LP into their priority list.

**Comment by Kuroichi-Neko** [comment]
I'm aware, but going crypto is currently not feasible idea.

**Comment by NicolasConstant** [comment]
Why?

**Comment by techtonik** [comment]
Yes, I am waiting for expanded answer too.

**Comment by aggsol** [comment]
In the EU you have to follow a lot of KYC rules when you work with crypto. Also the entry barrier for users is way higher than it was with SEPA transactions. See here how KYC is difficult: 

https://b-hive.eu/news-full/2017/6/8/kyc-in-europe-what-you-need-to-know

**Comment by techtonik** [comment]
From that article I only see that crypto makes most of this KYC cruft obsolete. Also I see that KYC is only needed when dealing with fiat. Nobody cares about your tokens as they mean nothing until converted to USD. So, LP can separate tokens into KYC-passed (means people already paid taxes from their donations) and KYC-undefined (means nobody cares where they come from and can just pass along).

**Comment by aggsol** [comment]
But LP still needs to convert my money to crypto and convert my crypto back to money. [Even crypto-to-crypto-only will likely fall into KYC/AML regulations](https://www.bna.com/insight-eu-regulation-n73014476945/). For recurring donations PayPal is now the gold standard :-(

**Comment by techtonik** [comment]
No, LP doesn't need to be an exchange. If LP is an exchange, then all pain with KYC are there, so if you can buy crypto at your local ATM, that's the best.

**Comment by MartinDelille** [comment]
There is a discussion about bitcoin started a long time ago: https://github.com/liberapay/liberapay.com/issues/364

**Comment by auge8472** [comment]
> so if you can buy crypto at your local ATM, that's the best.

I don't want to buy crypto at any ATM. I wan't to transfer and spend money of mine to people. To change the money into any crypto currency in a first step is an additional, laborious and unnecessary step.

**Comment by mnh48** [comment]
You'll also need to take into account countries where crypto is illegal or banned or not regulated or "banking banned", because in some places even purchasing crypto is not allowed.

For countries where it is not regulated, everyone involved at there are at risk in case anything went wrong with any crypto transaction (where normal bank transaction is protected under rules and could be reversed in case anything bad happened), no one want such risk for a simple donation.

**Comment by arthurgervais** [comment]
If you're interested in the legality of crypto (or Bitcoin), country by country, I can recommend https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country_or_territory

There are millions of people that already have cryptocurrencies and many different coins (see https://coinmarketcap.com/). I know that many would love to use them to donate.

The more cryptocurrencies you can accept, the merrier or am I missing something?

**Comment by techtonik** [comment]
> I don't want to buy crypto at any ATM. I wan't to transfer and spend money of mine to people. To change the money into any crypto currency in a first step is an additional, laborious and unnecessary step.

Can't you see from #232 that you can't just transfer and spend money - you need all kinds of permissions, and if you remember - getting your first cash into PayPal or bank account was harder than generating crypto wallet and sending some tokens there.

I see that Gratipocalypse didn't teach people anything. Looks like I should crowdsource to screen an anime about that together with 4chan..

**Comment by arthurgervais** [comment]
One of the biggest concerns of financial intermediaries is AML.

KYC/AML on crypto funds is a standard process that nearly any ICO nowadays does en masse. Doing so on smaller amounts for donation purposes is likely even easier from a regulatory point.

**Comment by auge8472** [comment]
> > To change the money into any crypto currency in a first step is an additional, laborious and unnecessary step.
> 
> Can't you see from #232 that you can't just transfer and spend money - you need all kinds of permissions, and if you remember - getting your first cash into PayPal or bank account was harder than generating crypto wallet and sending some tokens there.

You are kidding me, don't you? I know the topic of #232. I know, that bank transfers are currently not possible but they was it only one and a half week ago. *I want them to be possible again* in the near future. I want Mangopay to be *replaced by another, comparable service provider* to be able to transfer the money with a bank transfer again because it's one of the main and simplest ways to transfer money here in Europe. Transfer with CryptoAnything or PayPal or WhatEverYouWant can only be an additonal opportunity to bank transfers but *not the replacement* for it.

I do not want to be forced to take such an intermediate step over a crypto currency and definitely not the shady PayPal. If I can't use a simple bank transfer I will close my account because of the additional ((and for me) complicated) effort.

**Comment by techtonik** [comment]
@auge8472 I bet 0.025 ETH that you will not find non-crypto Mangopay replacement. Because bank regulations are about protecting big corps like PayPal and not simple folks like me and you. If you take another look at https://github.com/liberapay/salon/issues/247#issue-340382590 then you will see, that the first step is identifying origin and target. Once you've identified that origin and target are EU bank accounts, then you can research EU OpenAPI directive that promised to make transferring between banks possible without providers like Mangopay.

**Comment by techtonik** [comment]
But the thing is.. most likely you will still be using crypto https://ripple.com/ behind the scenes.

**Comment by auge8472** [comment]
> I bet 0.025 ETH that you will not find non-crypto Mangopay replacement.

Aha, MangoPay is the only service provider of that kind in the EU or complying the EU-regulations?

> If you take another look at #247 (comment) then you will see, that the first step is identifying origin and target. Once you've identified that origin and target are EU bank accounts, then you can research EU OpenAPI directive that promised to make transferring between banks possible without providers like Mangopay.

This would (if I doesn't misunderstood it) lead to LiberaPay being a licensed provider itself with costs of around 350k€ for the license.

**Comment by techtonik** [comment]
On Fri, Jul 20, 2018 at 4:34 PM Heiko August <notifications@github.com>
wrote:

> I bet 0.025 ETH that you will not find non-crypto Mangopay replacement.
>
> Aha, MangoPay is the only service provider of that kind in the EU or
> complying the EU-regulations?
>
I would say the only who was not easily complying, but now just the same as
others.

> If you take another look at #247
> <https://github.com/liberapay/salon/issues/247> (comment) then you will
> see, that the first step is identifying origin and target. Once you've
> identified that origin and target are EU bank accounts, then you can
> research EU OpenAPI directive that promised to make transferring between
> banks possible without providers like Mangopay.
>
> This would (if I doesn't misunderstood it) lead to LiberaPay being a
> licensed provider itself with costs of around 350k€ for the license.
>
It depends. It is EU citizens who should explain that to me. But if GDPR is
about me owning my own data, and directive is about the same (controlling
my own data), then no bank should prevent me from sending signed message
with my will to transfer my part of my balance to another individual. This
is the idea behind directive, which was transformed into Open Banking API,
because there was (and still is?) no understanding what blockchain is
about. And blockchain just implements it as this.
-- 
anatoly t.

**Comment by kindlyfire** [comment]
The pure fact alone that you would have to convert money into crypto, then exchange crypto, then convert crypto to money is discouraging for a big amount of our users. And then there are fees and fluctuations all along the way, which isn't nothing. Crypto isn't predictable. My euros are.

For all the time I have been receiving money on Liberapay, I haven't paid a dime (as in 0,00€) to transfer fees thanks to SEPA. This is not likely to be the case if we go crypto.

**Comment by MartinDelille** [comment]
@KindlyFire Crypto should never be a requirement to use Liberapay. Only another way to donate like euro and dollar. If we accept crypto, we should start with bitcoin that is the most common and *stable* one.

There is already an issue about it: https://github.com/liberapay/liberapay.com/issues/364

**Comment by NicolasConstant** [comment]
@MartinDelille If you go the crypto-road, you should have a look to Ethereum as well, because it support smart-contracts, and that would be a huge advantage for Liberapay because it solves the periodicity payment issue: you can plan future payments with Ethereum with this technology, and you totally can't with Bitcoin.

**Comment by MartinDelille** [comment]
@NicolasConstant This another issue that is (not very) discussed there: #14 

Do not [confound crypto and blockchain](https://github.com/liberapay/liberapay.com/issues/1224#issuecomment-415362779).

**Comment by techtonik** [comment]
[gitcoin.co grants](https://gitcoin.co/grants/) somewhat implements recurring donations in ETH, but their concept needs a better description. It is also AGPL and hence the code reuse is limited.

@kindlyfire hopefully 6 months later buying crypto is not a problem anymore, and if you get some crypto, you can use it right away on gitcoin.co to fund open source issues directly.

**Comment by NicolasConstant** [comment]
They're using smart-contracts as I was stating above, it's particularly adapted to this kind of usages.
Also, you can notice that they are compatible with DAI: an Ethereum Stable Coin (1 USD = 1 DAI) that solves the volatility issue of most cryptocurrencies.

Also, notice that DAI itself is handled by Ethereum smart-contracts, and only keeps the parity due to a set of economics incentives and games theory (please check this article for more info https://medium.com/@james_3093/the-dai-stablecoin-is-a-game-changer-for-ethereum-and-the-entire-cryptocurrency-ecosystem-13fb412d1e75 )
