### ISSUE TITLE
Inspire from Smartlike plateform

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#288]
@vadim-frolov posted this on the #1171 thread: https://smartlike.org/wiki/Micropayment_platform

It seems we have some common objective. Let's study this here.

**Comment by MartinDelille** [comment]
@vadim-frolov I don't understand what you mean here:

> 4. Go to Step 1 or Step 2 when smartlike becomes popular and Alice herself receives smartlike transfers from her audience, clients or employer.

**Comment by rugk** [comment]
Yet another cryptocurrency...

**Comment by vadim-frolov** [comment]
@MartinDelille Initially, the platform just efficiently pumps fiat from Alice to her favorite creators. That's what all micropayment services do. But Alice is a creator herself, even if she bakes cakes at an offline cafe. When the system grows, it has the potential to replace fiat with a less corrupt kind of money. (We started from these thoughts  - https://medium.com/@vadim.frolov/thank-u-value-and-money-redefined-on-blockchain-to-fix-ad-blocking-79de7a87231c )

@rugk Crypto and blockchain are just pieces of promising technology, even though they got compromised a bit by human greediness when badly configured. I learned about Liberapay a few hours ago and I like the concept and motivation. That's why I suggest improving it with whatever technology available. Liberapay implements a sort of gift economy, if I get it right, but builds it as an additional layer upon payment processors. This incurs obvious costs and vulnerabilities. Switching to a decentralized solution could simplify things (no user escrow accounts management, moderation, maintenance, electricity bills...), developers could focus on the code...
