### ISSUE TITLE
How to use Liberapay.com ?

### ISSUE THREAD

**Issue by Mikaela** [liberapay/salon#304]
I think I dropped out of how to use Liberapay.com when the move from Mangopay to PayPal/Stripe happened.

![How it works for donors index](https://user-images.githubusercontent.com/831184/57313346-f19a9080-70de-11e9-9734-0bebb3e81365.png)

Previously it used to just work, while now I was under impression that I have to register to Stripe and PayPal in order to be able to donate to projects using Liberapay and even now I cannot see how do I fund projects or my account or anything.

Could there be a more detailed step-by-step documentation (or even a video that I generally don't like) explaining how it works?

1. Register/press the pledge button.
2. Choose how much to donate.
3. ???

If I have funded my donations for a long time in advance, could there be something on the page telling me when I should expect a notification on my account needing funding?

**Comment by Changaco** [comment]
The process hasn't changed much for donors:

1. You go to a creator's donation page and choose the donation amount.
3. If necessary you log in or create your account.
4. You choose a payment method.
5. You choose a payment amount.
6. If the payment method is PayPal, then you're redirected there to confirm the payment, otherwise you input any necessary payment information (card or bank account number) “directly” in Liberapay.
7. The payment is initiated and its status is displayed. If you have other donations awaiting payment, then you're invited to fund them too.

The main difference compared to how Liberapay worked before is that the money you send goes directly into the accounts of people you donate to, instead of going into your account/wallet.

> I was under impression that I have to register to Stripe and PayPal in order to be able to donate to projects

[The “Payment Processors” page](https://liberapay.com/about/me/payment/) clearly states that “Donors do not need to connect any payment account below, they are only necessary to receive money”.

> If I have funded my donations for a long time in advance, could there be something on the page telling me when I should expect a notification on my account needing funding?

That information is in [your Giving page](https://liberapay.com/about/me/giving/).

**Comment by Mikaela** [comment]
Thanks, I don't understand how I missed that " Next payment in 1 month. " which all except the most recent one say.

**Comment by Mikaela** [comment]
And the last one gives me a new problem, is it recommended for me to not donate at all?

![Screenshot from 2019-05-08 23-44-50](https://user-images.githubusercontent.com/831184/57407205-29cecb80-71d2-11e9-8270-414f401f6a87.png)

**Comment by mattbk** [comment]
Mostly it looks weird (as you say at #975) because you're donating so little (which is fine!). The "not recommended, high fee percentage" is because of the 2.00 and 6.24 values--if you were donating 0.10 rather than 0.01, I think there would be a value without that warning. The fees are going to be there, and the more you donate at once, the less percentage goes to fees.

(Warning, I wander off into other ideas below.)

If you put 12.00 in, for example, the fee would be lower but you'd be reminded to donate again in ~24 years. If your "symbolic" level donations are reminders to someday increase them to something meaningful, you may want to increase the amount you're donating in order to be able to put (for example) a year's donation in at once and then be reminded annually.

This example would mean changing your donation to 12.00/year and putting in 12.00, but you could lower that to an amount you feel like you can afford.

**Comment by Changaco** [comment]
> if you were donating 0.10 rather than 0.01, I think there would be a value without that warning.

Actually, the donation amount only needs to be doubled to €0.02 per week.

![Screenshot_20190510_093309](https://user-images.githubusercontent.com/1581590/57510297-af539800-7306-11e9-9f13-31737d1dc497.png)

**Comment by Mikaela** [comment]
I ended up changing this donation to 0.02 €, but now it's inconsistent with the other donations I am making.

On increasing the donation amount more, I am currently donating to 9 projects and if I was to donate my funding to them all by 10 € simultaneously, there would be 90 € removed from my account in one go which I see as too high amount for now.

This is what I liked in Flattr, I could decide to e.g. pay 20 € / year to FOSS (usual association membership fee) and have Flattr share that 20 € to all the projects I was Flattring/subscribing without having to worry about 90 € fees for funding. I wish Liberapay could have something similar, I think you used to have an issue about it, but I was unable to find it with query `org:Liberapay Flattr`, but it's probably impossible now that you aren't actually holding money. It would also resolve my conscience issue of trying to donate to all projects equally especially as I don't have much to do with the projects I am donating to currently.

**Comment by Changaco** [comment]
The issue you were looking for is probably <https://github.com/liberapay/liberapay.com/issues/54>.
