### ISSUE TITLE
Liberapay Chargebacks

### ISSUE THREAD

**Issue by ghost** [liberapay/salon#401]
Hello there, I have a big concern about Chargebacks. Recently, I have had a conversation with multiple people about Chargebacks and I have been trying to avoid getting a Chargeback and so I came to ask if Liberapay has any sort of chargeback protection for incase a troll commits a chargeback?

**Comment by Changaco** [comment]
If there is a chargeback for a payment processed through Stripe, the money you had received is pulled back from your Stripe account. This can potentially lead to a negative balance, and to a debit of your bank account by Stripe in order to recover the funds. The amount of money pulled back from your Stripe account is always exactly the same amount you had received, the chargeback fee is paid by Liberapay. The final result is a net zero for you, and a net loss for Liberapay.

I don't know what PayPal does in case of chargeback.

---

P.S. [Chargebacks are mentioned in the FAQ](https://liberapay.com/about/faq#chargebacks):

> If despite our fraud prevention efforts you receive money whose origin is revealed to be fraudulent, it falls on you to pay it back.

**Comment by ghost** [comment]
Understood. I am starting to avoid the use of PayPal as a Twitch Affiliate and Streamer and have directed my payouts to Wire Transfer. Which is why I asked to have support for Payoneer.

**Comment by ghost** [comment]
Just a question, how can I accept Contributions on my Liberapay with Credit Card? I am slowly moving away from Paypal
