### ISSUE TITLE
Stripe Express Support?

### ISSUE THREAD

**Issue by ghost** [liberapay/salon#475]
Alright so, I have found a Stripe Product that seems to support my country and is used by other open source platforms such as GlimeshTV and Odysee.

Basicly, this is what the interface looks like when you log in:
![KobGQuTfD4](https://user-images.githubusercontent.com/37266538/144724261-12309b13-ff21-459f-ba01-342b15b1cc6b.png)

And this is what the dashboard looks like:
![librewolf_kCG3mqrmgQ](https://user-images.githubusercontent.com/37266538/144724310-e22b95e3-0db0-4ac8-b2de-fad041d96af4.png)

With Stripe Express, the LiberaPay Team can control the Flow of the funds recieved as well as the Payout Schedules.

Please consider this for those who are not on the Supported Country List of Stripe. :)

**Comment by Changaco** [comment]
Stripe Express accounts aren't available in more countries than other Stripe account types.

![Partial screenshot of the Stripe Connect settings regarding Express accounts, showing the list of supported countries](https://user-images.githubusercontent.com/1581590/144742902-4d533f0f-59c5-4348-90be-2f05232d35d0.png)

**Comment by ghost** [comment]
I know this issue is closed but I believe this documentation from Stripe is the latest:
https://stripe.com/docs/connect/cross-border-payouts

**Comment by Changaco** [comment]
Cross-border payouts are only available to platforms based in the US. We would need <https://github.com/liberapay/liberapay.org/issues/45> to use them.

**Comment by ghost** [comment]
Ahh ok, please do keep this Stripe Express in mind. Its going to help me and many others more as I am a resident in South Africa. What about this issue?

**Comment by Changaco** [comment]
After looking deeper into Express accounts again, here is a list of disadvantages:

1. Liberapay could go bankrupt in case of fraud (“For Express and Custom accounts, the platform is ultimately responsible to cover negative balances”, [Understanding Connect account balances](https://stripe.com/docs/connect/account-balances#accounting-for-negative-balances)). This means that we would have to manually review and approve accounts, either before allowing them to receive payments or before allowing them to withdraw their earnings.
2. There would be extra fees on payouts (see [Connect Pricing](https://stripe.com/connect/pricing)), and it's not clear to me how Liberapay would recover them.
3. Liberapay would once again be responsible for providing transaction records to users ([#714](https://github.com/liberapay/liberapay.com/issues/714)), because [the Express dashboard doesn't support exporting data](https://support.stripe.com/express/questions/can-i-export-a-list-of-my-payouts-from-stripe).

**Comment by ghost** [comment]
I 100% understand. Do whatever you feel is necessary and correct.

**Comment by Changaco** [comment]
Closing in favour of <https://github.com/liberapay/liberapay.com/issues/2238>.
