### ISSUE TITLE
Merge Watercooler and News labels

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#65]
I don't understand why we have both [Watercooler](https://github.com/liberapay/salon/labels/Watercooler) and [News](https://github.com/liberapay/salon/labels/News) labels.

Can't we merge them?

**Comment by Changaco** [comment]
The News label is a low-activity mailing list for our media managers, so that they can know what to share on social media without having to read everything that's being said in the salon.

The Watercooler is for Liberapay contributors (and people who care about everything that's happening to Liberapay even though they don't directly contribute right now).

**Comment by MartinDelille** [comment]
ok
