### ISSUE TITLE
Help for converting people to Liberapay

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/salon#66]
I tried (awkwardly maybe) to fund the Diaspora project through this issue: diaspora/diaspora#6575 (discussion start [here](https://github.com/diaspora/diaspora/issues/6575#issuecomment-239638009)).

Maybe someone can tell me what's wrong ?

**Comment by Changaco** [comment]
You made an unsolicited off-topic comment, you insisted after they had already told you no, and you didn't provide good arguments.

Bountysource is also open source and (partially) funded on their own platform. The difference in fees is not big enough to convince people, especially if you take into account that we have a pay-what-you-want fee (we ask users to donate to the Liberapay team) on top of payment processing fees.

It looks like most of the people you talked to are Europeans, so you could have mentioned that Liberapay is in Euros, but that wouldn't be enough to convince either.

The big issue is that starting to use Liberapay is not a simple thing to do for a big established project like Diaspora. There are two ways they could go: an organization account, or a team account. The first one isn't very interesting, and the second one would be a big change in how their project is funded, since it would mean adopting our take-what-you-want model. Just getting everyone on their team to agree to that would be a non-negligible amount of work, and you didn't give them any reason to try. Moreover, the prerequisite to trying something new is being unhappy with the status quo, but you haven't established that they're unhappy.

**Comment by MartinDelille** [comment]
Thank you for these wise words.

**Comment by MartinDelille** [comment]
I converted @Thomas101: https://github.com/Thomas101/wmail/issues/188#issuecomment-243064176

**Comment by davidak** [comment]
Can this issue be closed or is anything left to do?
