### ISSUE TITLE
Suggestions for 2017?

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#96]
What do you think the priorities should be for Liberapay in 2017? Which issues or missing features are hindering adoption? How much communication should we do and what should it focus on?

**Comment by Zatalyz** [comment]
Priority for developpement is close bug section : https://github.com/liberapay/liberapay.com/labels/Bug and Critical https://github.com/liberapay/liberapay.com/labels/Critical ;)

For communication : I want to go on RMLL and JDLL to make conference. If people want to make conference, I think it's a good thing. But it take time. 

Feature who are good : have a support ticket system (help desk), to manage mail and support user together. Actually, you are alone to manage it and it's not good : not resilient and a lot of work for you, while I can help on this things. I try [OStickets](http://osticket.com/) but I have little bug and so, maybe not good solution. Framasoft use [Request Tracker](http://request-tracker.fr/) (perl) but Framasky says "Hard to configure", so I don't try... however he propose to help us if we want this. Have a help desk is a good thing to manage community and ensure a good customer service.

More about communication... I haven't got luminous idea. Just an start of idea. Actually, funding is a hard job for people. It can be a good thing to open a project with other people in free world, about "how have money", and create articles, tools. If we host this documentation with the domain name Liberapay, it will offer a big visibility to your project. This will also be regular content to publish and so, something "visible" on social network. If people know we can help them, they come and use Liberapay :) 
But for that, I think we must have 3 tools : wiki, forum and pad (and IRC, but we have that). We can use etherpad from framasoft, or yours, or mine ; not a problem. For wiki, I advocate Dokuwiki, because I can manage it and I know it ; multilingue support is correct (less than mediawiki but more easy to configure) and really easy to use for other things. Forum, I don't know wich, but really, I think it's important. Github is actually ok for our use but : 
- we are dependant of a private company, we can't export and save our discussions
- it's not evident for people who are not informaticien...

I see a lot of forum in Django (python) but install django just for a forum is maybe too much ? 

Ok, so, my idea for the moment.

**Comment by Changaco** [comment]
Just a quick answer for now:

> we can't export and save our [GitHub] discussions

Of course we can. We can even import a whole project in GitLab and it'll contain pretty much everything that was in GitHub. There is no lock in.

**Comment by revi** [comment]
>Feature who are good : have a support ticket system (help desk), to manage mail and support user together. Currently, you are alone to manage it and it's not good : not resilient and a lot of work for you, while I can help on this things. I try OStickets but I have little bug and so, maybe not good solution. Framasoft use Request Tracker (perl) but Framasky says "Hard to configure", so I don't try... however he propose to help us if we want this. Have a help desk is a good thing to manage community and ensure a good customer service.

I agree with this and I'd like to help too if it's possible :D (and we may have additional queues, like abuse@liberapay.com, ....)

I have used [OTRS](https://www.otrs.com/download-open-source-help-desk-software-otrs-free/) as a user for a long time and it's very good imo as an agent (not sure about as a sysadmin and/or otrs admin - I once installed OTRS but it took few hours.). I have only used RT as a customer, just few times.

By the way, happy new year from 2017!

**Comment by Changaco** [comment]
Happy new year everyone :-)

**Comment by EdOverflow** [comment]
Happy New Year @Changaco!

**Comment by Changaco** [comment]
About the support@ email address: answering requests takes me some time, but not that much, and I'm the only who can answer most of them anyway. That's why I haven't taken the time to do #11 yet.

What does take time is maintaining social media accounts, but I've already tried to delegate that, with limited success: #29.

**Comment by Changaco** [comment]
> Priority for developpement is close bug section : https://github.com/liberapay/liberapay.com/labels/Bug and Critical https://github.com/liberapay/liberapay.com/labels/Critical ;)

Bugs and critical issues are always a priority, but the ones that are still open are either very hard to fix or not important enough for me to take care of immediately. Liberapay really has few bugs and except for the hosting issue it's in relatively good shape technically.

**Comment by Zatalyz** [comment]
Thanks Revi for come back about OTRS, I'll see that :)

And yes Changaco, social media is ... eeeeerk ! Worst job ? Sorry to not help you enough about that :/
